{
 "title": "Radix Node Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "query": "localhost:8099" },
   {
    "name": "datasource",
    "label": "Data Source",
    "query": "grafanacloud-<your grafana cloud name>-prom"
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Versions / Second",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(info_counters_sync_target_state_version{instance=\"$instance\"}[1m])"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(info_counters_sync_target_state_version{instance=\"$instance\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "info_counters_time_duration{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 9, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nodeinfo{instance=\"$instance\"}",
     "legendFormat": "{{ branch_and_commit }}"
    }
   ]
  },
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "View In Epoch",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "info_epochmanager_currentview_view{instance=\"$instance\"}",
     "legendFormat": "View"
    }
   ]
  },
  {
   "title": "Epoch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "info_epochmanager_currentview_epoch{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Address",
   "type": "stat",
   "gridPos": { "h": 2, "w": 18, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nodeinfo{instance=\"$instance\"}",
     "legendFormat": "{{ owner_address }}"
    }
   ]
  },
  {
   "title": "Registered Validator",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nodeinfo{instance=\"$instance\", validator_registered=\"true\"}"
    }
   ]
  },
  {
   "title": "Validator Address",
   "type": "stat",
   "gridPos": { "h": 2, "w": 18, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nodeinfo{instance=\"$instance\"}",
     "legendFormat": "{{ own_validator_address }}"
    }
   ]
  },
  {
   "title": "Node Key",
   "type": "stat",
   "gridPos": { "h": 2, "w": 18, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nodeinfo{instance=\"$instance\"}",
     "legendFormat": "{{ key }}"
    }
   ]
  },
  {
   "title": "Validator Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nodeinfo{instance=\"$instance\", is_in_validator_set=\"true\"}"
    }
   ]
  },
  {
   "title": "XRD Balance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "balance_xrd{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "XRD Staked",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 9, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "validator_total_stake{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Mempool Size",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "info_counters_mempool_count{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Mempool Additions / Second",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(info_counters_mempool_add_success{instance=\"$instance\"}[$__rate_interval])"
    }
   ]
  },
  { "title": "Radix Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Network Peers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "total_peers{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Network Peers Over Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "total_peers{instance=\"$instance\"}",
     "legendFormat": "Peers"
    }
   ]
  },
  {
   "title": "Network Validators",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "total_validators{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Network Validators Over Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 29 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "total_validators{instance=\"$instance\"}",
     "legendFormat": "Validators"
    }
   ]
  },
  {
   "title": "Proposal Made",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "info_counters_bft_proposals_made{}"
    }
   ]
  }
 ]
}